name: portfolio_danilo
description: "PortfÃ³lio profissional de Danilo A. Souza - Flutter Developer"
publish_to: 'none'

version: 4.0.0+17

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  responsive_builder: ^0.7.0
  
  # Animations
  animated_text_kit: ^4.2.2
  flutter_staggered_animations: ^1.0.0
  
  # Utilities
  url_launcher: ^6.2.4
  layout: ^1.0.5
  package_info_plus: ^4.2.0
  
  # Firebase
  firebase_analytics: ^10.8.5
  firebase_core: ^2.25.4
  firebase_core_platform_interface: ^5.0.0
  firebase_core_web: ^2.11.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: LandingPageIcons
      fonts:
        - asset: assets/fonts/LandingPageIcons.ttf
  